### ISSUE TITLE
I want to submit a Chinese language file.

### ISSUE THREAD

**Issue by dozbamb** [irtimaled/BoundingBoxOutlineReloaded#100]
I 'm sorry I make a issue for the thing.But I can't find the other way.I want to sumbit a chinese language file.Hope you can put it in mod.
[zh_cn.zip](https://github.com/irtimaled/BoundingBoxOutlineReloaded/files/4977355/zh_cn.zip)

**Comment by irtimaled** [comment]
Please add these to the Crowdin project
https://crowdin.com/project/boundingboxoutlinereloaded
