### ISSUE TITLE
Hasn't been working

### ISSUE THREAD

**Issue by carterartist** [irtimaled/BoundingBoxOutlineReloaded#106]
Before the recent update, I was not seeing the bounding boxes around fortresses, or some other features. still not seeing those and now I don't see the spawning spots anymore.

Mac. Fabric. Realms.

**Comment by irtimaled** [comment]
Please join the discord for help with seeing structure boxes when connecting to a unmodded server.

Spawnable spaces got broken by changes made by Mojang in 1.16.2. I’m working on a fix.

**Comment by carterartist** [comment]
Cool. Thank you. I wasn't criticizing and I'll check out the discord. I really do appreciate the work :)
