### ISSUE TITLE
all the versions not working for me I need 1.16.2 forge

### ISSUE THREAD

**Issue by ipunchyoucry** [irtimaled/BoundingBoxOutlineReloaded#107]
my minecraft cant load all the others mods pack verisons, i think cause only 1.16.2 can work. i went to see the neather fortress and open the bounding, it did not showed anything

**Comment by richardhopton** [comment]
There is no forge 1.16.2 version. Please use fabric.

**Comment by irtimaled** [comment]
There is no 1.16.2 version supported for forge. Please use fabric.

**Comment by ipunchyoucry** [comment]
Oh okay... But I’m in a server updated to 1.16.3 I downloaded that mod
pack. It did not show the boundaries like it did in some of the YouTube
videos. Can you tell me what’s wrong with it ?
