### ISSUE TITLE
Loading issue with Paper (1.16.4)

### ISSUE THREAD

**Issue by lachlancollins** [irtimaled/BoundingBoxOutlineReloaded#109]
Hi, I tried adding the Bukkit plugin to my Paper server (1.1.6.4 Build 294), and the server log became filled with the following message. A similar thing happened when migrating from 1.16.3 to 1.16.4 with some other plugins (e.g. Dynmap). Hope this information is helpful!

![image](https://user-images.githubusercontent.com/1667261/100420082-e69cbc00-30d9-11eb-8d57-b09ccc938124.png)

**Comment by irtimaled** [comment]
There is a new release of this currently in review on dev.bukkit.org. Alternatively you can build the code from the 1.16.4-bukkit branch if you are impatient ;)
