### ISSUE TITLE
How to build the fabric version?

### ISSUE THREAD

**Issue by JasonGoemaat** [irtimaled/BoundingBoxOutlineReloaded#112]
It looks like the source is setup for 1.14 and vanilla only.  I can't figure out how to build the fabric mod, even though there's a 1.16 version that seems to work.

**Comment by irtimaled** [comment]
Please use the correct branch name that targets fabric. Please note the current fabric release for 1.16.3 works fine with 1.16.4

**Comment by JasonGoemaat** [comment]
Wow, I feel dump.  I didn't even think about different branches for some reason.  I was able to build it and run it myself, thanks!  I sent you a donation using the link on curseforge, hope you got it.
