### ISSUE TITLE
1.16.5 FORGE clinet side only doesnt render boxes

### ISSUE THREAD

**Issue by FullMetalMaster** [irtimaled/BoundingBoxOutlineReloaded#116]
Heres an issue while on a vanilla server none of the boxes render at all correctly you get red lines aroudn spawn and green lines in the nether no red boxes at all (that would be a no dah add the mod into the server but can it be made to work only clinet side as well? 
![image](https://user-images.githubusercontent.com/52523300/107743368-c34bdb00-6cde-11eb-8834-16894a6953f9.png)

**Comment by irtimaled** [comment]
Please join the discord for support on what you can do to use this mod when connecting to the server. Due to lack of metadata on clients there is nothing that can be automatically to make this work with servers.
