### ISSUE TITLE
No mod icon

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [irtimaled/BoundingBoxOutlineReloaded#117]
No mod icon in ModMenu

**Comment by irtimaled** [comment]
I have no plans to take a dependency on some 3rd party mod.

**Comment by DragonEggBedrockBreaking** [comment]
You don't need to be dependent on ModMenu. You just need to put an icon in `src/main/resources/assets/modid/icon.png` and add a single line to `src/main/resources/fabric.mod.json`. If you don't use ModMenu, everything works the same, and no issues arise. If you use ModMenu, you see a mod icon there.
