### ISSUE TITLE
Fabric 1.16.1 support?

### ISSUE THREAD

**Issue by bananabenana** [irtimaled/BoundingBoxOutlineReloaded#119]
Hi, I love this mod and what it does on my SP fabric 1.16.3. Unfortunately, I run a fabric server for 1.16.1 and this causes the game to crash.
Is there any chance of support for this? If not, where should I be starting in terms of altering code?

Thanks!

**Comment by irtimaled** [comment]
I only support the latest patch release of the last 3 releases. if you join the discord server maybe someone has a build of for 1.16.1

**Comment by bananabenana** [comment]
Okay fair enough. Good tip, thanks
