### ISSUE TITLE
Will it be updated to version 1.17 in the future?

### ISSUE THREAD

**Issue by ktisme** [irtimaled/BoundingBoxOutlineReloaded#120]
I like this mod very much since version 1.16
I hope to continue to use this module in version 1.17

**Comment by surfrock66** [comment]
I poked through the code, it looks like there needs to be some structure definition updates for 1.17; it shouldn't be too hard, but I think if i understand it the API calls won't have changed too much?

**Comment by irtimaled** [comment]
Please visit the discord for announcements of new releases. The GitHub issues space is for issues with the mod.

**Comment by surfrock66** [comment]
FYI, when you try to join the discord you just get "whoops, unable to accept invite", not sure if that's on your side or a discord error?
