### ISSUE TITLE
Red Boxes

### ISSUE THREAD

**Issue by celsiusqc** [irtimaled/BoundingBoxOutlineReloaded#123]
So unless i am missing something, red boxes for nether fortress appear in singleplayer but not on a server. The boxes for a spawner appear on a server though. Is that normal?

**Comment by CyrusDe** [comment]
Having the same issue. The mod might need to be installed on the server side as well but I'm not sure.

**Comment by Breadabix** [comment]
Im having this issue with the mod on server and client. Spawning radius of spawners appears on server, as do slime chunks, but not the bounding box of the nether fortress.

**Comment by irtimaled** [comment]
Please join the discord server for support in setting up your system. GitHub issues are reserved for problems with the mod, not for support requests.

**Comment by Breadabix** [comment]
Id say its a problem with the mod if part of it isnt working in a situation many people play with.
