### ISSUE TITLE
I need a 1.17 jar

### ISSUE THREAD

**Issue by TheDevilCard** [irtimaled/BoundingBoxOutlineReloaded#125]
I need a 1.17 jar, but I can't find it. I hope the author will give me a link.，thanks.

**Comment by DereC4** [comment]
The reason you can't find it is because there's no 1.17 variant developed yet. Hope this helps and have a nice day!

**Comment by 9ikj** [comment]
#124

**Comment by irtimaled** [comment]
GitHub issues are reserved for problems with the mod, not for version requests.
