### ISSUE TITLE
When used with enhanced block entities chests are invisible

### ISSUE THREAD

**Issue by matthew2837** [irtimaled/BoundingBoxOutlineReloaded#126]
When I use the latest version of the 1.17.1 bbor with enhanced block entities (https://www.curseforge.com/minecraft/mc-mods/enhanced-block-entities) chests are invisible
![2021-07-26_19 40 10](https://user-images.githubusercontent.com/13020950/127072837-a38ef2bd-5f94-42be-ab3b-0d5dd4a9e034.png)

**Comment by irtimaled** [comment]
There is no official release of BBOR for 1.17.1 yet. Please hold off bug reports on incomplete development versions
