### ISSUE TITLE
Beacon overlay box only visible from the outside

### ISSUE THREAD

**Issue by Jeroen-45** [irtimaled/BoundingBoxOutlineReloaded#129]
In the 1.17.1 version you can only see the white faces of the beacon overlay when looking at it from the outside. When looking at the 'box' from the inside, you only see the white lines outlining the box, and not the white faces connecting it.

**Comment by ishland** [comment]
This is a known issue. 
https://github.com/irtimaled/BoundingBoxOutlineReloaded/pull/124#issue-696462419
