### ISSUE TITLE
/bbor:structures load, b+l, b+g dont work

### ISSUE THREAD

**Issue by carrotmafia** [irtimaled/BoundingBoxOutlineReloaded#131]
i tried on singleplayer, and a spigot server, both on 1.17, nothing happened when i did what is in the title

**Comment by Jeroen-45** [comment]
I am using the latest version taken from Curseforge(`BBOutlineReloaded-2.4-1.17.1-fabric-beta`), and I don't seem to have this issue. I haven't tested actually loading structures, but the B, B+G and B+L hotkeys all seem to work fine for me. I know you mentioned in Discord you tried it without any other mods, so I have no idea what would be causing the problem for you, I just though it might be helpful to add my experience. 

If it is of any help for resolving this, my system is running Windows 10 and I'm using fabric loader 0.11.6 with Minecraft 1.17.1.

**Comment by carrotmafia** [comment]
> I am using the latest version taken from Curseforge(`BBOutlineReloaded-2.4-1.17.1-fabric-beta`), and I don't seem to have this issue. I haven't tested actually loading structures, but the B, B+G and B+L hotkeys all seem to work fine for me. I know you mentioned in Discord you tried it without any other mods, so I have no idea what would be causing the problem for you, I just though it might be helpful to add my experience.
> 
> If it is of any help for resolving this, my system is running Windows 10 and I'm using fabric loader 0.11.6 with Minecraft 1.17.1.

i am using 1.17, not 1.17.1

**Comment by irtimaled** [comment]
Please use the supported version of Minecraft, in this case, 1.17.1.  Using a non supported version may exhibit issues due to incompatibilities between versions.
