### ISSUE TITLE
In server, the structures boundingbox don't display or display incorrectly

### ISSUE THREAD

**Issue by Shao-JinEi** [irtimaled/BoundingBoxOutlineReloaded#132]
In short, it doesn't work in server, but it can work in single world. I turned on the functions in the settings, and I entered the command "/bbor:seed 'server seed'", but it still doesn't display. 
The server doesn‘t have it installed

**Comment by irtimaled** [comment]
Please join the discord for support - there are additional steps you need to take to get structures working when connecting to a server.
