### ISSUE TITLE
Render issue with iris

### ISSUE THREAD

**Issue by fbano-0619** [irtimaled/BoundingBoxOutlineReloaded#134]
![image](https://user-images.githubusercontent.com/80695112/128661175-d73c5fb5-9c2e-4201-9e00-89102c568632.png)
Weired render issue when working with iris
![image](https://user-images.githubusercontent.com/80695112/128661353-539c6bb0-f505-469e-901e-1241c080514d.png)
And all mobs looks transparents.

**Comment by fbano-0619** [comment]
<img width="764" alt="屏幕截图 2021-08-09 125013" src="https://user-images.githubusercontent.com/80695112/128661591-c2269f8d-9d9f-45bd-bbc7-b394bb9fac62.png">
And I only have iris and BBOR in my mod folder, I disabled all other mods.

**Comment by ishland** [comment]
Please retest with #133

**Comment by fbano-0619** [comment]
So what should I do to get the updated mod?

**Comment by ishland** [comment]
Extract this and you will get that
[bbor-dev.zip](https://github.com/irtimaled/BoundingBoxOutlineReloaded/files/6952490/bbor-dev.zip)

**Comment by fbano-0619** [comment]
OK, it looks normal now
