### ISSUE TITLE
Mobs rendering error

### ISSUE THREAD

**Issue by V1K1NGbg** [irtimaled/BoundingBoxOutlineReloaded#135]
when I install this mod it "breaks" mobs textures. It looks like it turns them inside out and I can't figure out the reason, but when I remove the mod it goes back to normal

**Comment by ishland** [comment]
Duplicates https://github.com/irtimaled/BoundingBoxOutlineReloaded/issues/134
Fixed by #133 
See https://github.com/irtimaled/BoundingBoxOutlineReloaded/issues/134#issuecomment-894983070
