### ISSUE TITLE
nether fortress bounding boxes not showing up in 1.16.5

### ISSUE THREAD

**Issue by saitama245** [irtimaled/BoundingBoxOutlineReloaded#137]
it seems like everything else shows up but nether forts dont show up, blaze spawners do show up tho along with nether biomes like basalt and the forests

**Comment by Samuraien2** [comment]
same in 1.17

**Comment by irtimaled** [comment]
You are likely connecting to a server which does not have the mod installed on it. For workaround/support please join the discord
