### ISSUE TITLE
KeyboardListener is way too early for mod compatibility.

### ISSUE THREAD

**Issue by wagyourtail** [irtimaled/BoundingBoxOutlineReloaded#140]
I make a minecraft mod called `JSMacros` which does full keyboard handling for macros, this is supposed to be at a point where it doesn't get canceled by any other mod, therefore I inject at the head of the `Minecraft.keyboard.onKey` function, but BBOR overrides the GLFW keyboard listener so it goes though BBOR _before_ calling onKey... I would suggest making a more traditional keybind handler. 

Generally with mod compatibility, it's best to ask "if another mod does this hook in the same way, will it break one" for features that may be common between more than one mod; this is the case with `glfwSetKeyCallback`.

**Comment by irtimaled** [comment]
Happy to accept a pull request. Current handler works for forge, fabric & vanilla versions so reluctant to change

**Comment by ishland** [comment]
Closing as #148 is merged as 15388f47afe06591569f06a44df1c3be1f9761f8
