### ISSUE TITLE
Update to 1.18

### ISSUE THREAD

**Issue by mrGRINCH** [irtimaled/BoundingBoxOutlineReloaded#142]
Could you please update this for 1.18.

It's such a useful mod and I'm missing it.

**Comment by kkellogg378** [comment]
This. There's no other mod like it

**Comment by averwhy** [comment]
Bump

**Comment by irtimaled** [comment]
Please don’t use the GitHub issues for feature requests

**Comment by mrGRINCH** [comment]
Sorry, but there's no where else to contact you.
