### ISSUE TITLE
Error loading with 1.18+ 

### ISSUE THREAD

**Issue by halfhead** [irtimaled/BoundingBoxOutlineReloaded#144]
Getting this error message when trying to load only BBOR and fabric. BBOR version: BBOutlineReloaded-2.4-1.17.1-fabric-beta2.jar

The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: net/minecraft/class_4624
Exit Code: -1

 /Sadface

**Comment by irtimaled** [comment]
This mod does not currently support 1.18.1
