### ISSUE TITLE
Any plans on updating this essential mod?

### ISSUE THREAD

**Issue by XavierBit** [irtimaled/BoundingBoxOutlineReloaded#147]
I really miss BBOR in my 1.18 world...  :(

**Comment by MCPrime666** [comment]
me too

**Comment by KojiroMC** [comment]
bump because i used this mod so much. it was essential for me

**Comment by irtimaled** [comment]
Please don't spam the issues with update requests. Issues is for bugs with released versions of this mod, not for requests.

**Comment by X-Bit** [comment]
Spam? I would understand if you just said "nope, won't happen" or "leave me some time to work on it". But praising the mod and asking if there will be a continuation isn't spam, at least not in my book.

**Comment by irtimaled** [comment]
I’m glad you enjoy the mod, but this is also the 4th issue that has been raised on GitHub requesting this. Also get a bunch on curseforge and discord too. Please check historical closed issues before raising a new one.
