### ISSUE TITLE
Minecraft 1.7.10 client crashes on loading prexisting world(world created before mod was installed)

### ISSUE THREAD

**Issue by Zarklord1** [irtimaled/BoundingBoxOutlineReloaded#16]
http://pastebin.com/fjpREMfS is the log.
 it loads the world kinda, if i click on the world it starts loading it then crashes and stays on that screen forever and the only way to close minecraft is with taskmanager(windows)

**Comment by irtimaled** [comment]
Unable to reproduce - I am abandoning support for versions before 1.10.
