### ISSUE TITLE
Settings Button Mod compatibility

### ISSUE THREAD

**Issue by ghost** [irtimaled/BoundingBoxOutlineReloaded#161]
Hello, the settings button overlaps badly with other mods.
The mods:
https://www.curseforge.com/minecraft/mc-mods/spyglass-improvements
https://modrinth.com/mod/bedrockify

![image](https://user-images.githubusercontent.com/75373609/184933195-d9c51dee-0e58-4f83-9cc8-2fbf948a2f05.png)

Compatibility with the mods and/or the option to disable the option button and access it with a new keybind would be neat 😊
Awesome mod - greetings.

**Comment by ishland** [comment]
Fixed in c474d6f9b43e47357ff1bf1831892f0919a1e62f

The config menu is still accessible through ModMenu or key combo `b-c`
