### ISSUE TITLE
Stuck on load page

### ISSUE THREAD

**Issue by hurylove** [irtimaled/BoundingBoxOutlineReloaded#162]
Hello, I used your latest version 1.19.2 module on my 1.19.1 private server, but there was a problem that it would be stuck on the loading page when entering the game. I am not sure whether the module is incompatible with 1.19.1 or there are other problems. I wonder if you can answer them for me?

**Comment by irtimaled** [comment]
You can only use 1.19.2 version with a 1.19.2 server.
