### ISSUE TITLE
Stuck on loading terrain with Optifine

### ISSUE THREAD

**Issue by muink** [irtimaled/BoundingBoxOutlineReloaded#167]
### Client A "Test":
- Minecraft 1.19.2
- Forge 43.1.24
- Optifine HD_U_H9
- BBOutlineReloaded 2.5
- All configurations are default

### Client B "OoO":
- Minecraft 1.19.2
- All configurations are default
### Server:
- Spigot 1.19.2
- All configurations are default

## Description
I created a 1.19.2 Spigot server on my local computer, but when I log into the server with Client A, I get stuck on "loading terrain" page.
![A1](https://i.imgur.com/MuQyT7d.png)

So I use Client B to log into the server and find that Client A has Actually already entered the server (has the player entity).
![A1](https://i.imgur.com/zhIOEfa.png)

After killing Client A with the `/kill Test`, Client A enter the server, but the blocks and entities will not be displayed
![A1](https://i.imgur.com/kREA39y.png)  
![A1](https://i.imgur.com/Bt8AuZy.png)

Using BBO or Optifine alone will not encounter the above problems, is there any solution?

**Comment by s-yh-china** [comment]
theres currently no way to properly fix this problem.
the way optifine mod minecraft is too invasive

**Comment by irtimaled** [comment]
Optifine changes too much of the rendering pipeline. Closing as won't fix.
