### ISSUE TITLE
Minecraft 1.7.10 client crashes when hitting bounding box key (b for me) on a new world.

### ISSUE THREAD

**Issue by Zarklord1** [irtimaled/BoundingBoxOutlineReloaded#17]
http://pastebin.com/BtJe19xh is the log.
client loads new world generated(created after mod is installed)
when i hit the b key client grayscreens and the closes automaticaly.

**Comment by irtimaled** [comment]
Unable to reproduce - I am abandoning support for versions before 1.10.
