### ISSUE TITLE
Infinite loading of the world bug

### ISSUE THREAD

**Issue by MihailDenisov** [irtimaled/BoundingBoxOutlineReloaded#174]
Endless loading of the world when trying to connect to the server. In the debug console, rendering error spam is observed. At the same time, in a single game, the modification does not cause bugs. Perhaps it has something to do with interaction with Optifine or other mods.

When a bug occurs, the screen "loading terrain..." is displayed. Only stopping the game or the server helps.

[debug.log](https://github.com/irtimaled/BoundingBoxOutlineReloaded/files/9945613/debug.log)
[latest.log](https://github.com/irtimaled/BoundingBoxOutlineReloaded/files/9945614/latest.log)

**Comment by s-yh-china** [comment]
yes, bbor confilcts with optifine
theres currently no way to properly fix this problem.
