### ISSUE TITLE
Work Mod on 1.19.3

### ISSUE THREAD

**Issue by GroGaloraGran** [irtimaled/BoundingBoxOutlineReloaded#179]
Hello
please add the ability to use the mod on version 1.19.3 of the game.
seyas with this mod, with the latest version, we get an error "-1"
MOD version: BBOutlineReloaded-2.5-1.19.2-fabric
fabric-loader-1.19.3
release fabric-loader-0.14.11-1.19.3
error:
The game crashed whilst initializing game
Error: java.lang.IncompatibleClassChangeError: class com.irtimaled.bbor.client.gui.SettingsScreen$1 overrides final method net.minecraft.class_339.method_37020(Lnet/minecraft/class_6382;)V

![image](https://user-images.githubusercontent.com/57897389/208250705-bfd31019-349b-463c-8b9e-1cffeaf1b604.png)

**Comment by irtimaled** [comment]
You are getting this error because we have not yet released a version for 1.19.3 yet, and the 1.19.2 version will not work with any other version.
