### ISSUE TITLE
Magenta box in the nether?

### ISSUE THREAD

**Issue by trevorjd** [irtimaled/BoundingBoxOutlineReloaded#189]
Hi team,

Looking around for nether fortresses today and I spotted a magenta box when in the nether.  According to the description on Modrinth, this colour is only used for End Cities.  Any idea what this box is?  Seed is visible in the attached image.  Location and facing are visible in the minimap.  The box disappears if I get any closer.  I flew over there and can't spot anything, although it's hard to judge the distance since it disappears.

Thanks
![2023-06-23_15 07 20](https://github.com/irtimaled/BoundingBoxOutlineReloaded/assets/20573226/f41d8216-172e-4d36-a2f9-9e51fe8e465e)

**Comment by BloodshotPico** [comment]
Have you tried going over towards it and having a look?

**Comment by irtimaled** [comment]
Yeah, ruined portal
