### ISSUE TITLE
1.20.2

### ISSUE THREAD

**Issue by thesavagen** [irtimaled/BoundingBoxOutlineReloaded#197]
Can we get an update to 1.20.2? Thank you!

**Comment by perffeith** [comment]
Please 1.20.2

**Comment by nd002723** [comment]
[1.20.2-fabric-dev](https://github.com/irtimaled/BoundingBoxOutlineReloaded/suites/18584326231/artifacts/1079739316)

**Comment by swysgh** [comment]
It can works with 1.20.4

**Comment by LBL7647** [comment]
Can you resend it? The original one can't be downloaded anymore
