### ISSUE TITLE
[1.10.2] Client kicked on server login

### ISSUE THREAD

**Issue by dirtyfargo** [irtimaled/BoundingBoxOutlineReloaded#23]
**Description:** On login to server, client is kicked back to the menu screen. Works fine in single-player.

**Relevant part of the  server logs:** [fml-server-3.log](https://gist.github.com/dirtyfargo/9d477a8c1006e1a7dcc5c6e011121dfe) [I can send the full logs if needed.]

_On the client this appears on the screen when kicked:_ 
![7f59e3c6a7da19ff2de8d78e8fa3f58f](https://cloud.githubusercontent.com/assets/10457528/19319668/c33e3200-9062-11e6-8949-c09f6e988e16.png)

**Version:** 1.0.0 Beta 12
**Forge:** 12.18.2.2105

**Comment by barryashcroft** [comment]
Same issue here, running forge 12.18.2.2122.

Do we know what version of Java the mod was compiled against and also the Forge version tested against?

**Comment by irtimaled** [comment]
I'll be honest I've never tested against the latest forge server.  I'll look to spin one up and try to find a fix.

**Comment by barryashcroft** [comment]
What version did you test against, if you can remember that is ;). I'll give that a try as well...

**Comment by irtimaled** [comment]
The last version I tested was for forge 1.8... but that was beta 11 of the mod, not this version.
