### ISSUE TITLE
Compability with Random Things

### ISSUE THREAD

**Issue by lumien231** [irtimaled/BoundingBoxOutlineReloaded#24]
Got this crash report from a user: lumien231/Random-Things/issues/177

Any clue what is happening here?

**Comment by irtimaled** [comment]
Thanks for raising the issue. I would imagine it's something stupid I'm doing to work out how to handle the new dimension. I've never played modded before (I know right!!) so will have to setup a test env for it and repro - shouldn't be tricky.
