### ISSUE TITLE
No download

### ISSUE THREAD

**Issue by Nazta** [irtimaled/BoundingBoxOutlineReloaded#25]
If you are using instructions such as "just drop the jar file here", you should probably provide a link to the jar file.  or a link to the forum post, or something in the actual readme file on this page

**Comment by irtimaled** [comment]
Hey there,

Thanks for your interest in the mod.

Check out the GitHub releases section for downloads:- https://github.com/irtimaled/BoundingBoxOutlineReloaded/releases
Or the forum post for community assistance (and links back to the releases section):- http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2345401-bounding-box-outline-reloaded-mod-for-minecraft-1

Thanks, Irti
