### ISSUE TITLE
A few questions.

### ISSUE THREAD

**Issue by EmanYm** [irtimaled/BoundingBoxOutlineReloaded#26]
[Tango Tek brought me here](https://www.youtube.com/watch?v=1e4OH5AiHfY&list=PLnGKFxwFvsTg4KOqFeDwHvw5Eok4KCJ9v&index=23).

I have a question about something I am unclear on.
-Does every client require the jar if it's installed server-side?
-In order to use this on a server, do I put the designated .dat files into the server config folder, or my client config folder?
-If it is client side, do I need to periodically download and refresh the .dat files from the server, or will the .dat files automatically download new versions when something changes?

**Comment by irtimaled** [comment]
Hi EmanYm,

Thanks for trying out the mod - I hope you like it.

To answer your questions:-
1, Only clients that wish to display the bounding boxes need the mod installed
2, If you are using a forge server you can install this mod on the server and any forge clients will automatically get sent the bounding boxes without needing any copying of .dat files
3, If you want to run against a server without the mod installed (such as a vanilla server) then you will need to periodically copy the dat files from the server to the client. Slime chunks are based on an algorithm so these would continue to display in new chunks, but other structural bounding boxes would not unless you copy the files over.

**Comment by EmanYm** [comment]
Excellent!
So I can install this on the server and point my admins at the downloads.
Thank you for making something like this, it will become very handy

**Comment by EmanYm** [comment]
I have  1.0.0-Beta15 installed on a MC1.10.2 SpongeForge server.  I am unable to connect to that server through a Waterfall (Bungeecord alternative) network unless `[FMLMod:bbor{1.0.0-beta15}]` is on the client as well.
