### ISSUE TITLE
Plans to update to 1.12?

### ISSUE THREAD

**Issue by CoreyJ87** [irtimaled/BoundingBoxOutlineReloaded#27]
I just got into minecraft not too long ago and now am building a wither skeleton farm for the first time. This would be awesome to use. Although it broke for 1.12. Any chance you'd update this? I'm going to make an attempt at it. But I dont know much about writing forge mods. Only spigot. Thanks

**Comment by irtimaled** [comment]
This project uses MCP - there is a 1.12 pre 1 version available but no 1.12 final version.  Once there is a final version then I will recompile for 1.12.

**Comment by CoreyJ87** [comment]
Gotcha, awesome sounds good. Thanks

**Comment by darrenhollick** [comment]
I noticed a bunch of people asking on the forums if you're going to update the mod for 1.12. I have really enjoyed your mod and hope you will consider doing that as well. If it helps, I created a brand new Forge 1.12 server and only installed your mod and the crash report is attached.  I hope it might help.
[crash-report.txt](https://github.com/irtimaled/BoundingBoxOutlineReloaded/files/1107093/crash-report.txt)

**Comment by BrainStone** [comment]
Is there a serious harm by using the pre release? The differences between the pre versions and the final are usually not that big so that updating it again isn't much work (if any at all).

**Comment by irtimaled** [comment]
@BrainStone the 1.12 pre 1 version of MCP doesn't seem to work on my main development machine - all previous versions do tho.  I am also in the middle of moving from UK to USA, and living out of suitcases, so haven't had the time to try to figure out why it's not working!

**Comment by irtimaled** [comment]
@darrenhollick as stated 20 days ago I will upgrade to 1.12 as soon as I am able - see my previous comment from 1 minute ago to explain why that hasn't happened yet.

**Comment by BrainStone** [comment]
@irtimaled Ah ok. Didn't know that. That's of course a fair reason. I hope the relocation goes well and you can continue working on it again soon. :)

**Comment by darrenhollick** [comment]
I didn't know there was a pre release I will try that!  I hope your move goes well and that you can get settled.  Welcome to the U.S.!

**Comment by irtimaled** [comment]
https://github.com/irtimaled/BoundingBoxOutlineReloaded/releases/tag/1.0.0-beta17
