### ISSUE TITLE
Could install this mod by using launchwrapper?

### ISSUE THREAD

**Issue by wegood9** [irtimaled/BoundingBoxOutlineReloaded#31]
I have already modified 1.12.json like this and put the file into correct folder.

>	"libraries": [{
		"name": "optifine:OptiFine:1.12_HD_U_C5"
	},
	{
		"name": "bboutlinereloaded:BBOutlineReloaded:Vanilla1.12_1.0.0_beta17"
	},
	{
		"name": "net.minecraft:launchwrapper:1.12"
	}],

> 
I **could** lunch the game,but the mod didn't work.When I wanted to edit options-controls, the game crashed.

Reference:[This page](https://github.com/MultiMC/MultiMC5/wiki/Jar-Modding) shows the way to install a mod though launchwrapper.

**Comment by irtimaled** [comment]
This works with 1.0.4-beta2 for 1.13, 1.13.1 & 1.13.2.  Don't forget to add the tweak class.
