### ISSUE TITLE
Client Crash (ConcurrentModificationException)

### ISSUE THREAD

**Issue by Xogue** [irtimaled/BoundingBoxOutlineReloaded#33]
Not sure how to reproduce as I was just flying (elytra, if it matters) around without even showing the bounding boxes and it crashed. The crash log is attached. more info is freely given if there is something else I can tell you, I just cant think of what might help.

side note: thanks for this mod. It has helped so much already, and it should continue to help those who play my pack ;)

[crash-2018-01-19_19.13.43-client.txt](https://github.com/irtimaled/BoundingBoxOutlineReloaded/files/1649007/crash-2018-01-19_19.13.43-client.txt)

**Comment by kR1StYaN** [comment]
I got the same error. It crashes sometimes when i fly with my elytry and do some other stuff like eating. The crash is caused more often, since i build a villager breeder and some more iron farms. I also got some crashes in creative mode, when placing multiple villagers into a cell of an ordinary iron farm.

side node: I can just agree, that mod is amazing 👍 

[crash-2018-01-26_21.53.32-client.txt](https://github.com/irtimaled/BoundingBoxOutlineReloaded/files/1669386/crash-2018-01-26_21.53.32-client.txt)

**Comment by irtimaled** [comment]
Thanks for reporting this - I think I have the issue fixed so will product a build shortly.

**Comment by irtimaled** [comment]
https://github.com/irtimaled/BoundingBoxOutlineReloaded/releases/tag/1.0.2

**Comment by kR1StYaN** [comment]
Works really well now. In the old version a got up to 8 crashes a day. With the new version (1.0.2) i got just one in a test world. I was experimenting with some iron farms and entity cramming. My survival words did not crash one 👍 
I think there had been some iron farms at the border of my render distance. I did not move a lot when the game crashed.

[crash-2018-01-27_14.48.28-client.txt](https://github.com/irtimaled/BoundingBoxOutlineReloaded/files/1670243/crash-2018-01-27_14.48.28-client.txt)

**Comment by irtimaled** [comment]
Please give this version a try and let me know how you get on...
[BBOutlineReloaded-1.0.3-test-mc1.12.2.forge.jar.zip](https://github.com/irtimaled/BoundingBoxOutlineReloaded/files/1670447/BBOutlineReloaded-1.0.3-test-mc1.12.2.forge.jar.zip)

**Comment by kR1StYaN** [comment]
I'll try 👍

**Comment by kR1StYaN** [comment]
Did not crash for now. Runs just fine, but i could also not provoke a crash in 1.0.2 that was really random. I tried much more villages and different render distances. No problems.

**Comment by irtimaled** [comment]
Please don’t release this build - feel free to use it for now and I’ll probably put out a new build tonight/tomorrow

**Comment by irtimaled** [comment]
@Xogue I'd love to get your results from this latest version too.

**Comment by Xogue** [comment]
my apologies, Ill do some playing with it today and get back to you soon. :)

**Comment by Xogue** [comment]
Seems fairly stable at the moment. been flying around without issue. but as kR1StYaN said, it was random so you never know.

if the issue does come back, Ill be sure to post back here and let you know about it.
