### ISSUE TITLE
Mod won't install

### ISSUE THREAD

**Issue by LockManipulator** [irtimaled/BoundingBoxOutlineReloaded#34]
Not sure what "Copy the contents of the Vanilla archive into the JAR file as per usual. " means as you can't drag files into another file to combine them. I'm trying to install it on client side only so I use the vanilla zip file right? It's just filled with a bunch of random files and no JAR file. I tried to drag and drop them onto the Forge JAR file but that did nothing. I tried using just the Forge version and I can get into the game with no problems but if I create the folders and add the level.dat and Fortress.dat files in, then I get java.lang.NullPointerException as an error.

EDIT: Using the Forge version, it works on single player but changing the config to keep cache doesn't work. I go into single player world and load the structure (in this case, a nether fortress), then I exit the single player world, go into the multiplayer world at the same location, and nothing happens when I press the key to show the bounding box.

**Comment by irtimaled** [comment]
I assume you set the keep cache and then reloaded Minecraft?   What might make more sense is to grab the dat files from the singleplayer world and use these when connecting to the multiplayer server.  Have a look at the minecraft log for details of where it looks for the local structures.

**Comment by LockManipulator** [comment]
Grabbing the dat files from the singleplayer world worked, ty! :D

**Comment by irtimaled** [comment]
Great to hear!
