### ISSUE TITLE
Configuration does not generate when using LiteLoader

### ISSUE THREAD

**Issue by danruff5** [irtimaled/BoundingBoxOutlineReloaded#35]
I found out about LiteLoader and really liked the idea because I didn't want to install of Forge. But to use the BBOutline on a vanilla server one needs to have the config to either place the .dat files or turn on the cache. Once I installed Forge and loaded the mod it generated the config loading it with LiteLoader worked perfectly.

Versions in use:
BBOutlineReloaded-1.0.3-mc1.12.2
1.12.2-LiteLoader1.12.2
1.12.2-forge1.12.2-14.23.4.2705

**Comment by irtimaled** [comment]
This has been fixed in 1.0.4-beta2 - targeting vanilla 1.13, 1.13.1 & 1.13.2.  I need to look into side x side deployment with Liteloader

**Comment by irtimaled** [comment]
Closing since 1.13+ versions solve this and there is no 1.13+ version of liteloader and I am no longer able to maintain the code for 1.12.2
