### ISSUE TITLE
Crash when starting the game

### ISSUE THREAD

**Issue by maruohon** [irtimaled/BoundingBoxOutlineReloaded#4]
I get this crash when trying to start the game with the mod installed.
http://pastebin.com/YJHW1iKK

**Comment by richardhopton** [comment]
This might be the version of java i'm using.  I'm pretty sure the build process that forge provides uses java 7 but I'll double check and recompile.  I know it works with java 8 if that's any help in the meantime!

**Comment by irtimaled** [comment]
This was related to the java version used at compile time and a weird bug with covariance differences between java 7 and 8.  I've uploaded a fresh version with a fix for this.  Please confirm it works okay for you.

**Comment by irtimaled** [comment]
Sorry I should let you close the issue if you are happy it works for you

**Comment by maruohon** [comment]
Yes it works just fine now. Just tried it on my vanilla server with structure data copied to the client, and some known structures were showing up nicely. Thank you! :)
