### ISSUE TITLE
World Leaking on Server

### ISSUE THREAD

**Issue by mrgrim** [irtimaled/BoundingBoxOutlineReloaded#42]
When using this mod I get constant warnings of world leaks in my logs:

[16:47:13] [Server thread/DEBUG] [FML]: The world 35653db0 (GrimCraft) may have leaked: seen 25300 times.

I've observed this behavior on 1.0.1 and 1.0.3 for Forge 1.12.2-14.23.5.2808.

**Comment by irtimaled** [comment]
This is fixed in the 1.13.2 forge version
