### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by JTurn01** [irtimaled/BoundingBoxOutlineReloaded#43]
This issue is one that I know someone else is having as well.
I get this error when I try and startup the game on vanilla.

Name: bbor-1.0.5-1.13.2.jar
URL: https://libraries.minecraft.net/com/irtimaled/bbor/1.0.5-1.13.2/bbor-1.0.5-1.13.2.jar
Error details: HTTP 404: Not Found
Filename on disk: 893b-6944-951f-1bd1
Path: C:\Users\PCNAME\AppData\Local\Temp\893b-6944-951f-1bd1
Exists: file

Tried reinstalling minecraft to no avail, no other mods, installed through the vanilla installer you provided.

**Comment by irtimaled** [comment]
Duplicates #41
