### ISSUE TITLE
Version 1.0.6 boundaries loading bug

### ISSUE THREAD

**Issue by Darwign** [irtimaled/BoundingBoxOutlineReloaded#44]
So first of all I want you to know that I appreciate what you are doing and I'm really thankful of your mod it's a life saver. Just wanted to let you know that in your new version the villages boundaries are not always loading especially when they are too many together like an iron farm you need to place a new door to each village to make them update and appear which defeats the purpose. The same thing happens in all the new versions rift/vanilla/forge.

**Comment by irtimaled** [comment]
Interesting you mention forge because the forge version uses the old approach to village processing (because there aren't any hooks in forge for village changes)

Are you seeing this on client/server or client only versions?

**Comment by irtimaled** [comment]
Ahh I think I see the problem... thanks for bringing it to my attention

**Comment by Darwign** [comment]
I only ever used client only versions. Glad to see you already figured out the issue and by the way the new settings option is just perfect.

**Comment by irtimaled** [comment]
Fixed in 1.0.7
