### ISSUE TITLE
Inaccurate Slime chunks

### ISSUE THREAD

**Issue by gomsoop** [irtimaled/BoundingBoxOutlineReloaded#46]
Without knowing the seeds, this mod somewhat brings the players help to find some slime chunks. However in my experience, after knowing a seed in my multiplayer seed, the slime chunk that I was digging showed by BBOutlineReloaded was inaccurate. I hope there is an option to enter my seed and re-calculate slime chunks bounderies.

![Screen Shot at March 22nd 2019 - 5 13 48 am](https://user-images.githubusercontent.com/2426737/54782067-5e59e880-4c61-11e9-9383-bbca515d3b74.png)

**Comment by irtimaled** [comment]
Thanks for the report.  Were you using the client connecting to a server with the mod loaded?

**Comment by irtimaled** [comment]
Okay there's a weird bug where if you connect to a server without BBOR installed on the server, it will use the seed 0.  I will be fixing this bug in future versions.

To use the right seed on a multiplayer setup where you can't mod the server you can either get or create a level.dat file for the correct seed, and place it in the right folder in your minecraft folder.  This post from last year shows how to find out where BBOR looks for the files - https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2345401-bounding-box-outline-reloaded-mod-for-minecraft?comment=225
