### ISSUE TITLE
Rift version and OptiFine

### ISSUE THREAD

**Issue by ThexXTURBOXx** [irtimaled/BoundingBoxOutlineReloaded#47]
It seems like, the Rift version and OptiFine's Shaders aren't compatible (I tried to use Sildur's Vibrant Shaders).
I don't know, if there is a way to fix that, but it would be very cool if it's possible to use both alongside each other!
The mod loads correctly without any errors, but ingame, no boxes are shown.

**Comment by irtimaled** [comment]
This combination seems to work just fine.  Could this be related to the other issue you raised?
![2019-03-25_19 43 59](https://user-images.githubusercontent.com/10741555/54968028-6c945700-4f36-11e9-8772-f1a84261f56a.png)

**Comment by ThexXTURBOXx** [comment]
For me, the bounding boxes are still (1.0.9) not showing under some circumstances:
 - In certain viewing angles
 - In certain position (seems like e.g. near a village)

Additionally, the bounding boxes are pretty fuzzy:
![2019-03-26_11 32 16](https://user-images.githubusercontent.com/12763829/54990597-672d2000-4fbb-11e9-9c03-33dd31cbd0ce.png)
And when I go a few steps further to the village or change my viewing angle:
![2019-03-26_11 32 21](https://user-images.githubusercontent.com/12763829/54990602-698f7a00-4fbb-11e9-90a6-48dfdc56d4ee.png)
Did you really use the "Sildur's Vibrant shaders 1.20 Extreme"? That's the one I'm using. Yours seems more like the Lite version or something...
