### ISSUE TITLE
Unknown Spigot issue?

### ISSUE THREAD

**Issue by ThexXTURBOXx** [irtimaled/BoundingBoxOutlineReloaded#48]
I am trying to use Spigot and this mod together.
Unfortunately, I don't know exactly, where this problem arises, but this is my setup to reproduce it anyway:
 - Install BBOutlineReloaded-bukkit on Spigot server
 - Set Level Type to AMPLIFIED on server and let it generate the world
 - Install Rift 1.13.2 version of BBOutlineReloaded
 - Join Server and try to use the mod
Things like Mansions, Villages and so on won't get outlined. Slime Chunks show, however I don't know, if they are on the right locations...

**Comment by irtimaled** [comment]
Can you please try version 1.0.7 of the client side mod? Looks like I may have introduced a bug in 1.0.8

**Comment by ThexXTURBOXx** [comment]
Okay, where can I find this version? Seems like, the old versions have been removed from CurseForge

**Comment by ThexXTURBOXx** [comment]
I found the versions 1.0.4-rift and 1.0.6-rift through inofficial sources. The 1.0.4 does not work. The 1.0.6 however works. Can't test with 1.0.7-rift, because I can't find the jar anywhere.
Well, the server works in 1.0.6-rift, but in a singleplayer world (I just downloaded my server's world), it doesn't work. This is very weird

**Comment by irtimaled** [comment]
The old versions weren't removed, just archived - find them here...
https://minecraft.curseforge.com/projects/bounding-box-outline-reloaded/files?filter-status=2

This repo contains all the source for the rift mod - except for the Loader.java file that registers the mixins json file, and the riftmod.json file.

**Comment by irtimaled** [comment]
I believe this issue is resolved in 1.0.9 - released today. https://minecraft.curseforge.com/projects/bounding-box-outline-reloaded/files

**Comment by ThexXTURBOXx** [comment]
I'm not exactly sure, but I think, only the owner/author/... of the mod on CurseForge (only you) can see archived files of the mod... At least for me, only the newest files show up...

Ah okay, the absence of the riftmod.json file just confused me on this one.

And I tried 1.0.9 and it works fine. Thank you!
