### ISSUE TITLE
spawn chunk display too big (too many chunks)

### ISSUE THREAD

**Issue by therob** [irtimaled/BoundingBoxOutlineReloaded#53]
I could not reply at CurseForge, something in the text seems to look like a link...

So here is the problem with the marked spawn chunks in detail:

- the seed is -533884313
- the world spawn is at x:64, y:73, z:240
- MiniHUD displays chunks x:-4, z:7 to x:11, z:22 as lazy spawn chunks (correct)
- BBOR displays chunks x:-4, z:7 to x:12, z:23 as lazy spawn chunks (bugged)
- same problem exists for the entity processing spawn chunks
- the world was initially generated in MC 1.13 and updated to 1.13.1 and then 1.13.2 in a vanilla server (self-hosted)
- analysis was done with a copy in single-player with BBOR 1.0.10

I hope this helps.

**Comment by irtimaled** [comment]
This will be fixed in next release
