### ISSUE TITLE
[Bukkit/1.14] ChunkLoadEvent error

### ISSUE THREAD

**Issue by ThexXTURBOXx** [irtimaled/BoundingBoxOutlineReloaded#54]
Using BBOR 1.0.11 on Spigot 1.14 (latest build git-Spigot-c8d4cef-907de3f): https://hastebin.com/jilowohawe.rb
The message spams the whole server console (According to the Event's name maybe once for every chunk, that gets loaded?)

**Comment by irtimaled** [comment]
I just loaded the plugin with this download https://cdn.getbukkit.org/spigot/spigot-1.14.jar and it worked with no error.  Can you re-test with the latest version?

**Comment by ThexXTURBOXx** [comment]
That jar is by far not the latest version, sadly.
You have to run BuildTools with the --rev 1.14 (or now maybe --rev 1.14.1), so you get the latest Version.
If you run your Server jar and type in /version, it should say, that Updates are available.
