### ISSUE TITLE
GUI Controls: b and o key constantly overwritten on game startup

### ISSUE THREAD

**Issue by Knito58** [irtimaled/BoundingBoxOutlineReloaded#56]
BBOR 1.0.11-1.1.4
MC 1.14.1 Fabric API v0.1.0+59147463
In the controls GUI in the section "Bounding Box Outline Reloaded" the keys for "Toggle Active" and "Toggle Outer Box Only" are always set to "b" and "o" although I cleared them out because I use the BBOR-GUI from the esc menu only and have already set "b" and "o" to other mods.
After a fresh start of the game the first thing to do is to clear them out again because else they do not work as expected.

**Comment by irtimaled** [comment]
This is fixed in 1.0.12

**Comment by Knito58** [comment]
Thank you :)
