### ISSUE TITLE
Dont work with forge 1.13.2

### ISSUE THREAD

**Issue by 5QUAR3** [irtimaled/BoundingBoxOutlineReloaded#58]

**Comment by irtimaled** [comment]
Care to elaborate? There are many users who have confirmed it works fine so not sure why your experience differs.

**Comment by 5QUAR3** [comment]
when i launch it it says its not a valid mod file  using forge verson 25.0,219

**Comment by irtimaled** [comment]
Can you please confirm the file name of the BBOR mod you are trying using?

**Comment by 5QUAR3** [comment]
BBOutlineReloaded-1.0.11-13.2-vanilla.jar

**Comment by irtimaled** [comment]
Okay - this is not the forge version of the mod.  Please use the BBOutlineReloaded-1.0.11-1.13.2-forge.jar file instead.
