### ISSUE TITLE
Manual install on existing server?

### ISSUE THREAD

**Issue by rhullah** [irtimaled/BoundingBoxOutlineReloaded#59]
I'd like to install your mod into Carpet Mod (by [gnembon](https://github.com/gnembon/carpetmod)).  Is there a manual way I can drop the required class files into my existing Carpet Mod server jar file to add the functionality to Carpet Mod?  Or would there be too many conflicts?

Thanks!

**Comment by irtimaled** [comment]
I’m not sure how the carpet mod is installed. If it changes the server classes a lot it might not work. I’ll look into how it’s done and get back to you

**Comment by irtimaled** [comment]
I've reached out to gnembon but heard nothing in response. I guess they aren't interested in helping make this happen.
