### ISSUE TITLE
Nether Fortress Outlines Not Working

### ISSUE THREAD

**Issue by OzanKurt** [irtimaled/BoundingBoxOutlineReloaded#62]
What am I doing wrong?

I am using the 1.14 fabric version. The mod is installed both in server and client side.

![image](https://user-images.githubusercontent.com/8682003/59622189-2f082a00-9131-11e9-977f-54ac6fc64dd4.png)

**Comment by irtimaled** [comment]
Please can you confirm which version of the mod you are running on the client and server

**Comment by OzanKurt** [comment]
Both are the `BBOutlineReloaded-1.0.11-1.14-fabric.jar` from curseforge.

**Comment by OzanKurt** [comment]
I just added about 10 more mods, (literally some random mods like maps, iron chests...) and it started working. You can close the issue if you don't want to investigate further. Thanks!

**Comment by irtimaled** [comment]
I have occasionally seen weird issues with fabric - perhaps there was some mod conflicting?

**Comment by OzanKurt** [comment]
It was the only mod, I literally have no idea why it works in the overworld but not nether. I will open the issue again if that occurs during 1.14.3 upgrade.

**Comment by CRUSTAAY** [comment]
i had a simular issue, but i was able to fix it by removing my blockmeter mod

i am running BBOutlineReloaded-1.0.12-1.14.2-fabric.jar on my client and BBOutlineReloaded-1.0.12-1.14.2-bukkit.jar on my server

maybe its because both mods use the same color boxes (blockmeter and nether fortresses both use the same red boxes)

**Comment by irtimaled** [comment]
It might be that block meter doesn’t leave the renderer in the right state after its finished
