### ISSUE TITLE
 realm assistance 

### ISSUE THREAD

**Issue by feelsbadman123** [irtimaled/BoundingBoxOutlineReloaded#63]
I have I'm looking for help with getting Bounding Box Outline Reloaded Mod for Minecraft to work on my realm. I have it working in single player. I'm unsure where/how to "run" a command Minecraft (Java -jar BBOutlineReloaded-{version}.jar --server). Do I put this into the Minecraft launcher or in-game?

**Comment by irtimaled** [comment]
Hi there - This mod doesn't work with realms because the realms servers cannot be modded. If you run your own server (non-realm) then you can use the command as described.
