### ISSUE TITLE
No GUI and Keys don't work

### ISSUE THREAD

**Issue by Aangy** [irtimaled/BoundingBoxOutlineReloaded#64]
Hello,

My apologies if this has been covered elsewhere. I've searched extensively and couldn't find an answer.

When I try to use this mod, I can only get slime chunks to show. I press the B (remapped to I) and all it shows is the slime chunks. The O key does nothing, and I am unable to pull up the GUI. 

This does seem to work on single player, but not on the server that I run. It almost seems like BBOR is missing some information on the server. And I'm using the same seed for both. 

Can you help?

**Comment by irtimaled** [comment]
If you can see slime chunks then the mod is correctly loaded on the client.

To further assist you can you please confirm the version of the mod you have running on the client and server, whether you are running fabric/forge/risk/vanilla on the client, and what server software you are running.

**Comment by irtimaled** [comment]
What do you mean by “I’m using the same seed on both”?

**Comment by Aangy** [comment]
I am running 1.12.2 with forge installed. When you say server software, do you mean the mods?

By using the same seed, I mean the same seed I used on the server is also being used on the server.  For example, I can see witch hut boxes on single player, but can't see the box for the same witch hut on the server.

**Comment by irtimaled** [comment]
Are you able to reproduce this in 1.13 versions of the mod?

**Comment by Aangy** [comment]
I haven't tried since the mods I use are only available on 1.12.2. It just seems like seed information isn't being passed on properly. I'll try this with a new world and see if I get the same result.

**Comment by Aangy** [comment]
So I created the new world on the server and got the same result. What I've figured out is this:

-- Slime chunk and village spheres do render. Also the boundaries for igloos.
--Witch huts and water temple, and possibly other structures, do not render
--I have the default config, so these structures are set to true

One thing I forgot to mention... I do have Sponge installed with various plugins. Are there known issues there?

**Comment by Aangy** [comment]
Also see this from the server logs... For all intents and purposes, it seems this should be working. I just don't understand why it's not working. Any ideas would be appreciated.

[2019-06-25 19:57:08] [Server thread/INFO] [com.irtimaled.bbor.Logger]: send 1 entries to Aangy (OVERWORLD)[2019-06-25 19:57:53]
 [Server thread/INFO] [com.irtimaled.bbor.Logger]: remove 1 entry from Aangy (OVERWORLD)[2019-06-25 19:57:53] 
[Server thread/INFO] [com.irtimaled.bbor.Logger]: send 1 entries to Aangy (OVERWORLD)[2019-06-25 19:58:53] 
[Server thread/INFO] [com.irtimaled.bbor.Logger]: remove 1 entry from Aangy (OVERWORLD)[2019-06-25 19:58:53]

**Comment by Aangy** [comment]
Just wanted to let you know I figured it out. It appears something in Sponge won't let particular bounding boxes to appear. Unfortunately this means I uninstalled Sponge :)

**Comment by irtimaled** [comment]
I'm glad you figured out the cause.
