### ISSUE TITLE
fatal error on world load with 1.0.12-1.12.2-forge

### ISSUE THREAD

**Issue by WarlordWossman** [irtimaled/BoundingBoxOutlineReloaded#65]
So I updated to this new version and get an error that won't let me join any saves anymore, I was confused first because it still said 1.0.3 in mod options but confirmed this happens with 1.0.12-1.12.2-forge , here is a log:
https://gist.github.com/WarlordWossman/70d79d3eda291d1962476ddac1bf106c

**Comment by WarlordWossman** [comment]
Oh and idk how related that would be but I deleted the old cfg to make sure and it never generated a new one, not sure if that's related to the error or not but felt like I should also mention that.

**Comment by irtimaled** [comment]
I think the config is a red herring. The issue looks like how forge does stupid stuff with type casting.

**Comment by irtimaled** [comment]
I have a version of the mod that fixes this - would you be willing to beta test it since you saw the bug originally?

**Comment by WarlordWossman** [comment]
Sure, why not.

**Comment by irtimaled** [comment]
https://drive.google.com/file/d/14YunMYF5R2_iZKqGfvTFP5f6jS428Nzi/view?usp=sharing

**Comment by irtimaled** [comment]
Let me know how you get on and if it works for you too I'll put the same file on curseforge.

**Comment by WarlordWossman** [comment]
Seems like this one works, didn't get an error on world load!

**Comment by WarlordWossman** [comment]
There seems to be a lot of lof spam now tho in the form of:
`[04:02:29] [Client thread/INFO] [com.irtimaled.bbor.Logger]: Key: 32 = true`

Can't recall seeing so many messages like that before.

**Comment by irtimaled** [comment]
Okay - that was debug messaging for keyboard presses. I'm trying to figure out why press and hold isn't working

**Comment by WarlordWossman** [comment]
Another small detail I noticed with this version is that it doesn't draw the door lines for villages (and yes I have the config for them on "true").
