### ISSUE TITLE
Could we get a working Vanilla Installation for 1.14.2?

### ISSUE THREAD

**Issue by CaesarSaladMan** [irtimaled/BoundingBoxOutlineReloaded#67]
Because of the launcher redesign, the current Vanilla 1.14.2 installation doesn't work anymore. I still play on 1.14.2 because of some bugs with 14.3, and this mod would be super helpful. Could I get a working 1.14.2 installation, or at least instructions on how to fix the issue myself?

**Comment by irtimaled** [comment]
Keep an eye out on the curseforge page:- https://www.curseforge.com/minecraft/mc-mods/bounding-box-outline-reloaded/files/all
