### ISSUE TITLE
1.14.3 multiplayer

### ISSUE THREAD

**Issue by minecrafterseppe** [irtimaled/BoundingBoxOutlineReloaded#68]
i crash when i join my smp server 1.14.3 beta version of the mod
the non beta version isent even detected by forge as a mod file
 
[latest.log](https://github.com/irtimaled/BoundingBoxOutlineReloaded/files/3410960/latest.log)

**Comment by SocateId** [comment]
same here, I tried joining a server as well and it just crashes

**Comment by Moaxxe** [comment]
+1

**Comment by irtimaled** [comment]
This is resolved in the latest version.
