### ISSUE TITLE
Conflict with Recurrent Complex (1.12.2)

### ISSUE THREAD

**Issue by Tolerably** [irtimaled/BoundingBoxOutlineReloaded#71]
I installed BBOR alongside Recurrent Complex (among some other mods). The outline for slime chunks, spawn chunks, spawners, and villages rendered no problem, but none of the structure outlines (nether fortresses, desert temples, etc.) rendered.

When Recurrent Complex is removed, this issue does not occur (ie. the outlines render).

Recurrent Complex adds a bunch of structures to world gen. Could this be the source of the issue?

Using:
 - Recurrent Complex 1.4.8.2
 - BBOR 1.0.12
 - Forge 1.12.2-14.23.5.2838

**Comment by irtimaled** [comment]
RecurrentComplex completely changes how structures are generated in the world and as such I won't be able to support structure outlines in BBOR.
