### ISSUE TITLE
Not being recognized as a 1.14.4 mod

### ISSUE THREAD

**Issue by Drsnaki96** [irtimaled/BoundingBoxOutlineReloaded#72]
I have downloaded BBOutlineReloaded-1.0.13-1.14.4-forge.jar and forge seems to not recognize it as a 1.14.4 mod. There are is an error while loading the mod and it says that it requires minecraft 1.14.3 and that currently running 1.14.4 (which i am). I am using twitch launcher and forge 28.0.45, which as of the moment is the latest version. 
I also have 11 other mods and a few data packs

**Comment by irtimaled** [comment]
This is now resolved. Please download a new version from curseforge.
