### ISSUE TITLE
Feature Request: Placeable 128-radius Bounding Sphere

### ISSUE THREAD

**Issue by robpaveza** [irtimaled/BoundingBoxOutlineReloaded#73]
Hey there. I see you've already got a bounding sphere option for villages, so I'm hoping that this feature ask will be doable (I may fork and try to do this, but I haven't built any Minecraft mods yet).

Basically: I want to stand on a block and press some kind of key (let's say Ctrl+B) and that will create a bounding sphere centered at the block that I'm standing on with a 128-block radius.  This will be useful for creating the light-level / slabbing / etc. perimeter needed for AFK platforms for things like witch farms, slime farms, generalized mob farms, etc. etc.  The sphere should persist until the keypress is pressed again or until you log off.

What do you think about something like this?  Thanks!

**Comment by irtimaled** [comment]
This feature (or something very similar) is already on the discord feature suggestions channel.

**Comment by irtimaled** [comment]
I’m closing the issue since there isn’t an issue that is causing the mod to not work correctly.
