### ISSUE TITLE
Implement permission nodes

### ISSUE THREAD

**Issue by Huskehhh** [irtimaled/BoundingBoxOutlineReloaded#74]
Hey, just an idea. Would love to be able to control who can see the data provided through the Bukkit plugin. 👍 

boundingboxoutlinereloaded.*
boundingboxoutlinereloaded.stronghold
boundingboxoutlinereloaded.mineshaft
...etc

Thanks!

**Comment by irtimaled** [comment]
This feature suggestion was raised in the discord. Would love your input on this feature request over there.
