### ISSUE TITLE
Can't connect to forge server without mod installed on client

### ISSUE THREAD

**Issue by LyraelRayne** [irtimaled/BoundingBoxOutlineReloaded#75]
Also cannot connect to a forge server with the mod installed on client but not on the server.

The error message for the failure is "Connection closed - mismatched mod channel list" 

This happens using `BBOutlineReloaded-1.0.13-1.14.4-forge.jar` in minecraft 1.14.4 Forge 28.1.40.

**Comment by irtimaled** [comment]
This issue has already been fixed. Please join the discord server and ask in support
