### ISSUE TITLE
Boxes not always visible through other blocks with alwaysVisible=true (1.15.1)

### ISSUE THREAD

**Issue by ariosos** [irtimaled/BoundingBoxOutlineReloaded#78]
Set alwaysVisible=true and reload the game.
Press B to activate the bounding boxes.
Bounding boxes will not be visible until the player picks up an item, then it displays for roughly a tick or so.

Mods: Forge 30.0.15
BBOutlineReloaded-1.0.14-1.15.1-forge
ClothConfig2-2.0
LightOverlay-4.1

Seed: 6763240565142953728
(Nice little survival island, BTW)

**Comment by irtimaled** [comment]
This is fixed in the next release
