### ISSUE TITLE
Keep Cache not working between single and multiplayer.

### ISSUE THREAD

**Issue by StevenMLocke** [irtimaled/BoundingBoxOutlineReloaded#80]
Using 1.15.1 with fabric loader.  I have changed the 'keep cache' config line to 'true'. closed and reloaded the game entirely.  I have a single player creative world built from the exact seed of the multiplayer server.  When I load the single player world, I am using bbor to outline the biomes, which works fine. I then save and quit, without closing the game, and log into the multiplayer server and the biome outlines are no longer there.

The bbor ver that I have installed is BBOutlineReloaded-1.0.14-1.15.1-fabric.

**Comment by irtimaled** [comment]
Biome outlines don’t need to be cached because servers send this data to the client (it’s in the F3 screen) - as a result the mod doesn’t cache them.
