### ISSUE TITLE
Witch Hut not showing

### ISSUE THREAD

**Issue by purestone9** [irtimaled/BoundingBoxOutlineReloaded#81]
I have the config file as the default witch lets the witch hut box be drawn but it is not being drawn.

I am playing of the Vanilla Sky Block 1.15 map

![image](https://user-images.githubusercontent.com/29181158/76486016-beeab400-63e3-11ea-98b2-414505a537e9.png)

**Comment by irtimaled** [comment]
can you share a copy of the world and the location of the witch hut

**Comment by irtimaled** [comment]
or is this a server?

**Comment by purestone9** [comment]
its on a server

**Comment by purestone9** [comment]
67.60.132.9:25568

**Comment by irtimaled** [comment]
I assume the server doesn't have the mod installed.

**Comment by purestone9** [comment]
no

**Comment by purestone9** [comment]
im guessing that is the issue then?

**Comment by irtimaled** [comment]
then it won't work without installing the mod on the server. this is not an issue. for workarounds please join the discord linked from curseforge.
