### ISSUE TITLE
[Feature Request] Biome borders fixed at Y level

### ISSUE THREAD

**Issue by DuelMonster** [irtimaled/BoundingBoxOutlineReloaded#83]
I've been trying to map out a river biome for a build I'm working on and have found it difficult to get an overview of the biome without placing temporary blocks along the perimeter.

It would be great in you could add an option to fix the biome border to a Y level like the spawn slime chunks have.

Mock up:

![image](https://user-images.githubusercontent.com/5095995/78594954-147a7b00-7841-11ea-8ecc-17d979a12fda.png)

**Comment by irtimaled** [comment]
This will be released in the next version of BBOR.
