### ISSUE TITLE
Doesn't work in the nether on multiplayer

### ISSUE THREAD

**Issue by jamjamreeree** [irtimaled/BoundingBoxOutlineReloaded#85]
The mod works perfectly fine in single player (both in the overworld and nether). However, in multiplayer, the mod seems to work only in the overworld and not in the nether? Is there a way I can fix this?

**Comment by irtimaled** [comment]
Please join the discord and read the second FAQ post which describes how to get structures to display when connecting to a multiplayer server.

**Comment by TwoSpicy** [comment]
Hello, can I ask where I can find your discord server?

**Comment by irtimaled** [comment]
It’s linked at the top of the curseforge project page. https://discord.gg/4ZJpJvh
