### ISSUE TITLE
Not showing the pillager spawning area at outpost

### ISSUE THREAD

**Issue by yangzhaofeng** [irtimaled/BoundingBoxOutlineReloaded#88]
According to the minecraft wiki,

> Pillagers naturally spawn and respawn in outposts. They spawn in a 72×54×72 block area centered on the top floor (with the chest).

But BBOR is not showing such area, but a strange combination instead
![image](https://user-images.githubusercontent.com/5832364/80606815-50cb8080-8a67-11ea-8209-3044639b9999.png)

Is it possible for it to show the spawning area?

**Comment by irtimaled** [comment]
Please switch to the Outer Box Only using the GUI or by pressing B+O.
