### ISSUE TITLE
2.0-1.15.2 doesn't load.

### ISSUE THREAD

**Issue by JillSwift** [irtimaled/BoundingBoxOutlineReloaded#92]
Fabric loader (0.8.3-build-196) doesn't seem to see the BBOutlineReloaded-2.0-1.15.2-vanilla.jar

No error messages in the log.
No sign of the mod in Minecraft.

[BBOR_Launch_Log.txt](https://github.com/irtimaled/BoundingBoxOutlineReloaded/files/4646629/BBOR_Launch_Log.txt)

**Comment by irtimaled** [comment]
Please use the fabric file with the fabric loader
