### ISSUE TITLE
Not valid file type

### ISSUE THREAD

**Issue by angry-overweight-apple-employee** [irtimaled/BoundingBoxOutlineReloaded#93]
I'm no programmer so please excuse if I describe things wrong or if I'm overlooking something obvious
I've downloaded 2 versions, one that ended in bukkit.jar and one that ended in vanilla.jar. I use Forge to run the mod in the game and this is the first mod I've tried to install. Both files the game told me it was an invalid file type for a mod when I opened it.

**Comment by irtimaled** [comment]
Please use the forge file.
