### ISSUE TITLE
error cannot load main class.

### ISSUE THREAD

**Issue by Jester295** [irtimaled/BoundingBoxOutlineReloaded#96]
I've downloaded the main .jar file but it seems that the class is missing or not connecting. what do I do?

PS C:\WINDOWS\system32> java -jar "C:\Users\Eagle eye\Downloads\BBOutlineReloaded-2.2-1.16.1-fabric.jar"
Error: Could not find or load main class com.irtimaled.bbor.Main

**Comment by irtimaled** [comment]
Not sure why you are trying to open the fabric version by double clicking on it. Just drop it in the mods folder and open fabric 1.16.1
