### ISSUE TITLE
Rendering errors in fabulous mode

### ISSUE THREAD

**Issue by Ranlajetech** [irtimaled/BoundingBoxOutlineReloaded#98]
The outlines of Slime Chunks and some other structures are rendered strangely in fabulous mode.

Affects Version:{
  BBOR: BBOutlineReloaded-2.2-1.16.1-fabric,
  Fabric: fabric-loader-0.9.0+build.204-1.16.1,
  Minecraft: 1.16.1
}

![2020-07-20_11 48 31](https://user-images.githubusercontent.com/56589757/87902282-c6a21f80-ca8b-11ea-9747-f2423e5c8a66.png)
![2020-07-20_13 19 22](https://user-images.githubusercontent.com/56589757/87902290-c99d1000-ca8b-11ea-910f-5edd8a5ba6cb.png)
![2020-07-20_13 19 41](https://user-images.githubusercontent.com/56589757/87902291-cace3d00-ca8b-11ea-96d4-3a8d76f2d17b.png)

As a comparison, this is the render in 'Fancy' mode:

![2020-07-20_13 39 53](https://user-images.githubusercontent.com/56589757/87903876-aa07e680-ca8f-11ea-9957-c204c07bbf5a.png)

**Comment by irtimaled** [comment]
This is much better in 2.3 release...

**Comment by Ranlajetech** [comment]
The issue mentioned before has been resolved.

However, there are still some problems. The "fill" of "Slime Chunks" rendered incorrectly in fabulous mode.

Looing aside in fancy:
![away_fancy](https://user-images.githubusercontent.com/56589757/91592941-dfa6c600-e991-11ea-969a-ceca71383b59.png)

In fabulous("fill" is on, just not rendered):
![away_fabulous](https://user-images.githubusercontent.com/56589757/91593150-390ef500-e992-11ea-91fa-38dd5846340c.png)

When I flying trough the border, only part of it is rendered:
![in_fabulous](https://user-images.githubusercontent.com/56589757/91593023-0664fc80-e992-11ea-9ea0-bade006dbc9b.png)

Other Borders also have the same problem.

-----

Affects Version: {
BoundingBoxOutlineReloaded: 2.3-1.16.2-fabric
Minecraft: 1.16.2
Fabric Loader: 0.9.2+build.206-1.16.2
Fabric API: fabric-api-0.19.0+build.398-1.16
}

**Comment by irtimaled** [comment]
Yeah the fill is something I’m aware of. Not a lot I can do.

**Comment by Gorrrg** [comment]
masady's MiniHUD has the same problem, but it's worse. The boxes are totally opaque. Seems like whatever alpha level either mod uses is round up or down to 100% or 0% opacity by the _Fabulous!_ shaders.

**Comment by Gorrrg** [comment]
masady's MiniHUD doesn't have this problem in Fabulous! mode though, so it is possible to get opacity levels in that rendering mode. (If you see the slime chunk all opaque in MiniHUD, it's because you have to set the alpha level of the slimeChunkOverlayColor to something other than 0xFF20F020, something more reasonable like 0x8020F020).
